### PR TITLE
Remove unused images.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by patrickhlauke** [comment]
sorry, i'm using the pictures folder as a bit of a dumping ground of both used and now-obsolete images, for reference to myself (i occasionally dig through to find how, for instance, a particular browser behaved). this probably goes into how i (ab)use this particular repo myself

**Comment by XhmikosR** [comment]
All right, I thought you just left them there.

**Comment by patrickhlauke** [comment]
My disorganised messy nature, publicly revealed ;)

**Comment by XhmikosR** [comment]
No worries, it's your repo anyway :)

About the other branches perhaps rehashing will help too if they have
unmerged patches. Otherwise the repo is pretty big just so you know.

**Pull request closed without merging**
