### PR TITLE
Losslessly compress images.

### PR DESCRIPTION
**Pull request by XhmikosR**
```
Before: 60.1 MB (63.129.508 bytes)
After:  56.3 MB (59.153.927 bytes)
```

### CODE REVIEW

**Comment by patrickhlauke** [comment]
What compression tool/settings did you use? I usually (though some may have slipped through) run pngs through pngcrush

**Comment by XhmikosR** [comment]
Rebased.

I used optipng, pngout, deflopt. And then passed everything with kraken.io in lossless mode.

I use zopfli too, but the images are so many so I skipped that for now.

**Comment by patrickhlauke** [comment]
at that stage, i think i do need to start thinking about some build tool (or just a grunt script to run image optimisations on the pictures folder)...thanks for this!

**Comment by XhmikosR** [comment]
It would complicate things a little bit but yeah.

Another thing I was thinking is that you should resize some of those huge images like background-cover.jpg.

I'm gonna look into lazy loading later, but it might be trickier with shower.

**Comment by patrickhlauke** [comment]
Yeah shower might put a spanner in the works. I'll look at those large jpgs and see how much I can squeeze out of them manually.

**Comment by XhmikosR** [comment]
Can you also remove any obsolete branches?

**Comment by patrickhlauke** [comment]
i like to keep individual presentations i did in their branches,,,the main gh-pages is the complete evergreen(ish) set, while individual presos are usually a culled/edited version

**Comment by patrickhlauke** [comment]
Ref https://github.com/patrickhlauke/getting-touchy-presentation/commit/da8f3b8a8aebc02430198a4c2a8baf2b33b2145b

Before: 56.3MB / After: 30.6MB

**Pull request merged**
